//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sdl.Community.ArgosTranslateProvider {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MtProviderConfDialogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MtProviderConfDialogResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sdl.Community.ArgosTranslateTradosPlugin.MtProviderConfDialogResources", typeof(MtProviderConfDialogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Cancel.
        /// </summary>
        public static string btn_Cancel_Text {
            get {
                return ResourceManager.GetString("btn_Cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;OK.
        /// </summary>
        public static string btn_OK_Text {
            get {
                return ResourceManager.GetString("btn_OK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete saved access keys.
        /// </summary>
        public static string btnDeleteSavedCreds_Text {
            get {
                return ResourceManager.GetString("btnDeleteSavedCreds_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send plain text only (no tags).
        /// </summary>
        public static string chkPlainTextOnly_Text {
            get {
                return ResourceManager.GetString("chkPlainTextOnly_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Re-send draft and translated segments.
        /// </summary>
        public static string chkResendDrafts_Text {
            get {
                return ResourceManager.GetString("chkResendDrafts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save access keys for future sessions.
        /// </summary>
        public static string chkSaveKey_Text {
            get {
                return ResourceManager.GetString("chkSaveKey_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        public static System.Drawing.Icon form_Icon {
            get {
                object obj = ResourceManager.GetObject("form_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string form_Text {
            get {
                return ResourceManager.GetString("form_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert here your API key.
        /// </summary>
        public static string groupBox3_Text {
            get {
                return ResourceManager.GetString("groupBox3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provider Options.
        /// </summary>
        public static string groupBox4_Text {
            get {
                return ResourceManager.GetString("groupBox4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOTE: once keys have been saved, they can be deleted by pressing the delete button,.
        /// </summary>
        public static string KeyForm_SaveKeyTooltip1 {
            get {
                return ResourceManager.GetString("KeyForm_SaveKeyTooltip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a or by leaving box unchecked and clicking &apos;Ok&apos;..
        /// </summary>
        public static string KeyForm_SaveKeyTooltip2 {
            get {
                return ResourceManager.GetString("KeyForm_SaveKeyTooltip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simply removing the provider will not delete the keys after they have been saved..
        /// </summary>
        public static string KeyForm_SaveKeyTooltip3 {
            get {
                return ResourceManager.GetString("KeyForm_SaveKeyTooltip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File error.
        /// </summary>
        public static string lookupFileStructureCheckErrorCaption {
            get {
                return ResourceManager.GetString("lookupFileStructureCheckErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was a problem with the selected file:.
        /// </summary>
        public static string lookupFileStructureCheckGenericErrorMessage {
            get {
                return ResourceManager.GetString("lookupFileStructureCheckGenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was a problem loading the file: &apos;{0}&apos;. Make sure the contents are properly-formatted XML according to the required specifications, which are described in the plugin&apos;s documentation..
        /// </summary>
        public static string lookupFileStructureCheckXmlProblemErrorMessage {
            get {
                return ResourceManager.GetString("lookupFileStructureCheckXmlProblemErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authentication.
        /// </summary>
        public static string tabPage1_Text {
            get {
                return ResourceManager.GetString("tabPage1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other options.
        /// </summary>
        public static string tabPage3_Text {
            get {
                return ResourceManager.GetString("tabPage3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please correct the following problem(s):.
        /// </summary>
        public static string validationMessageHeader {
            get {
                return ResourceManager.GetString("validationMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A translation engine must be selected. If no engine is shown, please check your API key..
        /// </summary>
        public static string validationMessageNoEngine {
            get {
                return ResourceManager.GetString("validationMessageNoEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a When access key auth method is selected, the region endpoint name and both access keys must be specified.
        /// </summary>
        public static string validationMessageNoKey {
            get {
                return ResourceManager.GetString("validationMessageNoKey", resourceCulture);
            }
        }
    }
}
